name: attendance
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_theme_switcher: ^2.0.10
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  device_preview: ^1.3.1
  dio: ^5.9.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.9.1
  flutter_cached_pdfview: ^0.4.3
  flutter_local_notifications: ^19.4.1
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_sticky_header: ^0.8.0
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.12
  get: ^4.7.2
  get_cli: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  logger: ^2.5.0
  mime: ^2.0.0
  package_info_plus: ^8.1.1
  photo_view: ^0.15.0
  rename: ^3.1.0
  retrofit: ^4.6.0
  shared_preferences: ^2.5.3
  timelines_plus: ^1.0.7
  unique_identifier: ^0.4.0
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null
  json_serializable: null
  retrofit_generator: null
# flutter_native_splash:
#   color: "#EFEFEF"
#   image: assets/images/splash12.png
#   android_12:
#     image: assets/images/splash12.png
#     color: "#EFEFEF"
#   android: true
#   ios: true
#   web: true
# dev_dependencies:
#   build_runner: null
#   flutter_gen_runner: null
#   flutter_lints: ^4.0.0
#   flutter_test:
#     sdk: flutter
#   hive_generator: ^2.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    # - assets/flags/ #comment when doing flutter packages pub run build_runner build --delete-conflicting-outputs
    - assets/fonts/
    - assets/locales/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 800
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
