// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-754UXsTLKc_H7fhzAJjQm9-wQooHsQ',
    appId: '1:72543078307:web:55cc0cbe1081f8bf9dfc16',
    messagingSenderId: '72543078307',
    projectId: 'attendance-c7666',
    authDomain: 'attendance-c7666.firebaseapp.com',
    storageBucket: 'attendance-c7666.firebasestorage.app',
    measurementId: 'G-RT8QWS2Z8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAs1K6VHHEmkEbu7ynl27rDQca1kBSLlA',
    appId: '1:72543078307:android:57e5c1efa1e6498a9dfc16',
    messagingSenderId: '72543078307',
    projectId: 'attendance-c7666',
    storageBucket: 'attendance-c7666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANAl0vmlY5ze_2j9XqeD9Bw0st59wN1P4',
    appId: '1:72543078307:ios:07e2efb07922dcae9dfc16',
    messagingSenderId: '72543078307',
    projectId: 'attendance-c7666',
    storageBucket: 'attendance-c7666.firebasestorage.app',
    iosBundleId: 'com.almahd.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANAl0vmlY5ze_2j9XqeD9Bw0st59wN1P4',
    appId: '1:72543078307:ios:0bdd4c63b1169fa89dfc16',
    messagingSenderId: '72543078307',
    projectId: 'attendance-c7666',
    storageBucket: 'attendance-c7666.firebasestorage.app',
    iosBundleId: 'com.almahd.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3-754UXsTLKc_H7fhzAJjQm9-wQooHsQ',
    appId: '1:72543078307:web:df16d7f3490690939dfc16',
    messagingSenderId: '72543078307',
    projectId: 'attendance-c7666',
    authDomain: 'attendance-c7666.firebaseapp.com',
    storageBucket: 'attendance-c7666.firebasestorage.app',
    measurementId: 'G-6NNYPRGKPF',
  );
}
